# Generated by Django 4.2.7 on 2025-10-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={},
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cod", max_length=50),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="cart",
            table=None,
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="order",
            table=None,
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="passwordresettoken",
            table=None,
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
        migrations.AlterModelTable(
            name="profile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="review",
            table=None,
        ),
        migrations.AlterModelTable(
            name="store",
            table=None,
        ),
    ]
